### ISSUE TITLE
aiortc install error on aarch64

### ISSUE THREAD

**Issue by supermanhuyu** [jlaine/aiortc#126]
on my Nvidia-Jetson-tx2 (aarch64, ubuntu 16 )
i compiled opencv and  ffmpeg 3.4.5 with  `configure --disable-static --enable-shared --disable-doc`
and install aiortc get some error about `pylibsrtp` and `crc32c`

```
$ ffmpeg 
ffmpeg version 3.4.5 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --disable-static --enable-shared --disable-doc

```

```
$ pip install aiortc
Collecting aiortc
Requirement already satisfied: attrs in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aiortc) (18.2.0)
Collecting aioice<0.7.0,>=0.6.12 (from aiortc)
  Using cached https://files.pythonhosted.org/packages/4c/02/b137c98041d4fcd1319eda0c4fa1a0cd121dfa2fcdff573be8d7ed0452f8/aioice-0.6.12-py3-none-any.whl
Requirement already satisfied: pyopenssl in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aiortc) (18.0.0)
Requirement already satisfied: cffi>=1.0.0 in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aiortc) (1.11.5)
Requirement already satisfied: cryptography>=2.2 in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aiortc) (2.4.2)
Collecting pylibsrtp>=0.5.6 (from aiortc)
  Using cached https://files.pythonhosted.org/packages/75/ab/bca419472cf7171b42aa56d977a6d1263ceadaf454c082a151cbad566b74/pylibsrtp-0.6.0.tar.gz
Collecting crc32c (from aiortc)
  Using cached https://files.pythonhosted.org/packages/c4/fb/bc0eb23d0c5fd167b159a50ebcbcdc34bf661b0ea132453d792b8739886a/crc32c-1.6.tar.gz
Requirement already satisfied: pyee in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aiortc) (5.0.0)
Requirement already satisfied: av<7.0.0,>=6.1.0 in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aiortc) (6.1.0)
Requirement already satisfied: netifaces in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from aioice<0.7.0,>=0.6.12->aiortc) (0.10.6)
Requirement already satisfied: six>=1.5.2 in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from pyopenssl->aiortc) (1.11.0)
Requirement already satisfied: pycparser in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from cffi>=1.0.0->aiortc) (2.19)
Requirement already satisfied: asn1crypto>=0.21.0 in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from cryptography>=2.2->aiortc) (0.24.0)
Requirement already satisfied: idna>=2.1 in ./py_env/kr214_tf1110/lib/python3.5/site-packages (from cryptography>=2.2->aiortc) (2.7)
Building wheels for collected packages: pylibsrtp, crc32c
  Running setup.py bdist_wheel for pylibsrtp ... error
  Complete output from command /home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-feokhe7x/pylibsrtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-pmzhkmji --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.5
  creating build/lib.linux-aarch64-3.5/pylibsrtp
  copying pylibsrtp/__init__.py -> build/lib.linux-aarch64-3.5/pylibsrtp
  copying pylibsrtp/tests.py -> build/lib.linux-aarch64-3.5/pylibsrtp
  running build_ext
  generating cffi module 'build/temp.linux-aarch64-3.5/pylibsrtp._binding.c'
  creating build/temp.linux-aarch64-3.5
  building 'pylibsrtp._binding' extension
  creating build/temp.linux-aarch64-3.5/build
  creating build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/nvidia/py_env/kr214_tf1110/include/python3.5m -c build/temp.linux-aarch64-3.5/pylibsrtp._binding.c -o build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5/pylibsrtp._binding.o
  build/temp.linux-aarch64-3.5/pylibsrtp._binding.c:492:24: fatal error: srtp2/srtp.h: No such file or directory
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pylibsrtp
  Running setup.py clean for pylibsrtp
  Running setup.py bdist_wheel for crc32c ... error
  Complete output from command /home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-feokhe7x/crc32c/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7h21ltna --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'crc32c' extension
  creating build
  creating build/temp.linux-aarch64-3.5
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNDEBUG -I. -I/usr/include/python3.5m -I/home/nvidia/py_env/kr214_tf1110/include/python3.5m -c _crc32c.c -o build/temp.linux-aarch64-3.5/_crc32c.o -O3
  _crc32c.c:69:15: error: ‘crc32c_crc32_sw’ undeclared here (not in a function)
    {"crc32_sw", crc32c_crc32_sw, METH_VARARGS, "Calculate crc32c using a software implementation."},
                 ^
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for crc32c
  Running setup.py clean for crc32c
Failed to build pylibsrtp crc32c
Installing collected packages: aioice, pylibsrtp, crc32c, aiortc
  Running setup.py install for pylibsrtp ... error
    Complete output from command /home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-feokhe7x/pylibsrtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-e7910jig/install-record.txt --single-version-externally-managed --compile --install-headers /home/nvidia/py_env/kr214_tf1110/include/site/python3.5/pylibsrtp:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.5
    creating build/lib.linux-aarch64-3.5/pylibsrtp
    copying pylibsrtp/__init__.py -> build/lib.linux-aarch64-3.5/pylibsrtp
    copying pylibsrtp/tests.py -> build/lib.linux-aarch64-3.5/pylibsrtp
    running build_ext
    generating cffi module 'build/temp.linux-aarch64-3.5/pylibsrtp._binding.c'
    creating build/temp.linux-aarch64-3.5
    building 'pylibsrtp._binding' extension
    creating build/temp.linux-aarch64-3.5/build
    creating build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/nvidia/py_env/kr214_tf1110/include/python3.5m -c build/temp.linux-aarch64-3.5/pylibsrtp._binding.c -o build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5/pylibsrtp._binding.o
    build/temp.linux-aarch64-3.5/pylibsrtp._binding.c:492:24: fatal error: srtp2/srtp.h: No such file or directory
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-feokhe7x/pylibsrtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-e7910jig/install-record.txt --single-version-externally-managed --compile --install-headers /home/nvidia/py_env/kr214_tf1110/include/site/python3.5/pylibsrtp" failed with error code 1 in /tmp/pip-install-feokhe7x/pylibsrtp/

```

**Comment by jlaine** [comment]
There is a problem with the new version of crc32c which was uploaded today, the source tarball is incorrect. This is tracked here:

https://github.com/ICRAR/crc32c/issues/8

**Comment by supermanhuyu** [comment]
@jlaine after update the crc32c to 1.7 version , i still get the install  error of the `pylibsrtp`  on aarch64.


```
$ pip install aiortc
Building wheels for collected packages: pylibsrtp
  Running setup.py bdist_wheel for pylibsrtp ... error
  Complete output from command /home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ba10098y/pylibsrtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-s4h5qjec --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.5
  creating build/lib.linux-aarch64-3.5/pylibsrtp
  copying pylibsrtp/__init__.py -> build/lib.linux-aarch64-3.5/pylibsrtp
  copying pylibsrtp/tests.py -> build/lib.linux-aarch64-3.5/pylibsrtp
  running build_ext
  generating cffi module 'build/temp.linux-aarch64-3.5/pylibsrtp._binding.c'
  creating build/temp.linux-aarch64-3.5
  building 'pylibsrtp._binding' extension
  creating build/temp.linux-aarch64-3.5/build
  creating build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/nvidia/py_env/kr214_tf1110/include/python3.5m -c build/temp.linux-aarch64-3.5/pylibsrtp._binding.c -o build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5/pylibsrtp._binding.o
  build/temp.linux-aarch64-3.5/pylibsrtp._binding.c:492:24: fatal error: srtp2/srtp.h: No such file or directory
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pylibsrtp
  Running setup.py clean for pylibsrtp
Failed to build pylibsrtp
Installing collected packages: pylibsrtp, aiortc
  Running setup.py install for pylibsrtp ... error
    Complete output from command /home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ba10098y/pylibsrtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-h32f2vd8/install-record.txt --single-version-externally-managed --compile --install-headers /home/nvidia/py_env/kr214_tf1110/include/site/python3.5/pylibsrtp:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.5
    creating build/lib.linux-aarch64-3.5/pylibsrtp
    copying pylibsrtp/__init__.py -> build/lib.linux-aarch64-3.5/pylibsrtp
    copying pylibsrtp/tests.py -> build/lib.linux-aarch64-3.5/pylibsrtp
    running build_ext
    generating cffi module 'build/temp.linux-aarch64-3.5/pylibsrtp._binding.c'
    creating build/temp.linux-aarch64-3.5
    building 'pylibsrtp._binding' extension
    creating build/temp.linux-aarch64-3.5/build
    creating build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/nvidia/py_env/kr214_tf1110/include/python3.5m -c build/temp.linux-aarch64-3.5/pylibsrtp._binding.c -o build/temp.linux-aarch64-3.5/build/temp.linux-aarch64-3.5/pylibsrtp._binding.o
    build/temp.linux-aarch64-3.5/pylibsrtp._binding.c:492:24: fatal error: srtp2/srtp.h: No such file or directory
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/nvidia/py_env/kr214_tf1110/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ba10098y/pylibsrtp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-h32f2vd8/install-record.txt --single-version-externally-managed --compile --install-headers /home/nvidia/py_env/kr214_tf1110/include/site/python3.5/pylibsrtp" failed with error code 1 in /tmp/pip-install-ba10098y/pylibsrtp/

```

do you know the problem ? 
thanks .

**Comment by gemfield** [comment]
```bash
#if ubuntu
apt install libsrtp2-dev
```

**Comment by AbdallahAlhaddad** [comment]
The problem isn't with  the`ARM64` architecture.
I was able to solve my problem  by doing the [this](https://github.com/PyAV-Org/PyAV/issues/619#issuecomment-765639402).
#### this solution tested on:

- `Ubuntu 18.04` 
-  jetson nano board (`aarch64 processor` )

**Comment by jlaine** [comment]
FYI there are now binary wheels for `pylibsrtp` on aarch64.

**Comment by micaelillos** [comment]
For macbook: ```brew install srtp```

**Comment by LeoDog896** [comment]
On Fedora, use `sudo dnf install libsrtp-devel`
